spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
    globally_quoted_identifiers: true
  datasource:
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://godsaengdb.cpvbdgo8npm2.ap-northeast-2.rds.amazonaws.com:3306/jewelry
    username: root
    password: rkdtlstjd

cloud:
  aws:
    stack:
      auto:false
    region:
      static: ap-northeast-2
    credentials:
      access-key:
      secret-key:
    s3:
      bucket: jewelrybucket

frontend:
  base:
    url:

server:
  port: 8070